/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        background: "#eff7fe",
        surface: "#eff7fe",
        "surface-bright": "#eff7fe",
        "surface-dim": "#c9d6e0",
        "surface-variant": "#d2dee8",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#e9f2fa",
        "surface-container": "#dfeaf2",
        "surface-container-high": "#d9e4ed",
        "surface-container-highest": "#d2dee8",
        primary: "#5a3bdd",
        "primary-dim": "#4e2bd1",
        "primary-container": "#a192ff",
        "primary-fixed": "#a192ff",
        "primary-fixed-dim": "#9481ff",
        secondary: "#00666a",
        "secondary-dim": "#00595d",
        "secondary-container": "#00f4fe",
        "secondary-fixed": "#00f4fe",
        "secondary-fixed-dim": "#00e5ee",
        tertiary: "#a12b76",
        "tertiary-dim": "#911c69",
        "tertiary-container": "#ff8acb",
        "tertiary-fixed": "#ff8acb",
        "tertiary-fixed-dim": "#f974c1",
        error: "#b41340",
        "error-dim": "#a70138",
        "error-container": "#f74b6d",
        outline: "#70787e",
        "outline-variant": "#a6aeb5",
        "on-background": "#283035",
        "on-surface": "#283035",
        "on-surface-variant": "#545d62",
        "on-primary": "#f6f0ff",
        "on-primary-container": "#210077",
        "on-primary-fixed": "#000000",
        "on-primary-fixed-variant": "#2a0091",
        "on-secondary": "#c9fcff",
        "on-secondary-container": "#00575b",
        "on-secondary-fixed": "#004346",
        "on-secondary-fixed-variant": "#006266",
        "on-tertiary": "#ffeff4",
        "on-tertiary-container": "#620044",
        "on-tertiary-fixed": "#360024",
        "on-tertiary-fixed-variant": "#720050",
        "on-error": "#ffefef",
        "on-error-container": "#510017",
        "inverse-surface": "#070f14",
        "inverse-on-surface": "#969ea4",
        "inverse-primary": "#917eff",
      },
      borderRadius: {
        DEFAULT: "1rem",
        lg: "2rem",
        xl: "3rem",
        full: "9999px",
      },
      fontFamily: {
        headline: ["Space Grotesk", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
      },
      boxShadow: {
        glass: "0 8px 32px 0 rgba(123,97,255,0.08)",
      },
    },
  },
  plugins: [],
}
