/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        "primary": "#68519d",
        "primary-container": "#af96e8",
        "on-primary": "#ffffff",
        "on-primary-container": "#422b75",
        "secondary": "#83478c",
        "secondary-container": "#f8b1ff",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#783d81",
        "tertiary": "#006a65",
        "tertiary-container": "#00b7ae",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#00423e",
        "background": "#faf8fe",
        "on-background": "#1a1b1f",
        "surface": "#faf8fe",
        "on-surface": "#1a1b1f",
        "surface-variant": "#e3e2e7",
        "on-surface-variant": "#494550",
        "outline": "#7a7581",
        "outline-variant": "#cbc4d1",
        "error": "#ba1a1a",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f4f3f8",
        "surface-container": "#efedf2",
        "surface-container-high": "#e9e7ec",
        "surface-container-highest": "#e3e2e7",
      },
      fontFamily: {
        headline: ["'Space Grotesk'", "sans-serif"],
        body: ["Inter", "sans-serif"],
      },
      borderRadius: {
        "2xl": "1.5rem",
        "3xl": "2rem",
        "4xl": "2.5rem",
      },
    },
  },
  plugins: [],
};
